[BUTTONS]
South = "Enter"
East = "Space"
North = "PageDown"
West = "PageUp"
C = ""
Z = ""
LeftTrigger = "Right" #MouseButton
LeftTrigger2 = "Control"
RightTrigger = "Left" #MouseButton
RightTrigger2 = "Alt"
Select = "Tab"
Start = "Escape"
Mode = ""
LeftThumb = ""
RightThumb = ""
DPadUp = "UpArrow"
DPadDown = "DownArrow"
DPadLeft = "LeftArrow"
DPadRight = "RightArrow"
Unknown = ""

[JOYSTICK_Z]
LeftZ = "ModeChange"
RightZ = "Shift"