[offset]
left = 0
right = 0

[deadzone]
left = 0.5
right = 0.5

[chords]
chord_0 = "osentiah"
chord_1 = "0123456789"
chord_2 = ""
chord_3 = "uyrclmdw"
chord_4 = ""
chord_5 = ""
chord_6 = ""
chord_7 = "bxfvgkpj"
