[offset]
left = 
right =

[deadzone]
left = 0.5
right = 0.5

[chord_0]
note_0 =
note_1 =
note_2 =
note_3 =
note_4 =
note_5 =
note_6 =
note_7 =

[chord_1]
note_0 =
note_1 =
note_2 =
note_3 =
note_4 =
note_5 =
note_6 =
note_7 =

[chord_2]
note_0 =
note_1 =
note_2 =
note_3 =
note_4 =
note_5 =
note_6 =
note_7 =

[chord_3]
note_0 =
note_1 =
note_2 =
note_3 =
note_4 =
note_5 =
note_6 =
note_7 =

[chord_4]
note_0 =
note_1 =
note_2 =
note_3 =
note_4 =
note_5 =
note_6 =
note_7 =

[chord_5]
note_0 =
note_1 =
note_2 =
note_3 =
note_4 =
note_5 =
note_6 =
note_7 =

[chord_6]
note_0 =
note_1 =
note_2 =
note_3 =
note_4 =
note_5 =
note_6 =
note_7 =

[chord_7]
note_0 =
note_1 =
note_2 =
note_3 =
note_4 =
note_5 =
note_6 =
note_7 =